### ISSUE TITLE
Define extra Python env requirements on top of root directory requirements.txt

### ISSUE THREAD

**Issue by biphasic** [jupyterhub/mybinder.org-user-guide#286]
Not all the dependencies that might be necessary in a binder environment are always present in the root requirements.txt, sometimes they are split into other files.

### Proposed change

It would be great to be able to define extra environment dependencies that are not just in the root requirements.txt file. My library has another requirements.txt in the docs folder, to run the notebooks for example.

### Who would use this feature?

Anyone who has separate dependencies for testing/documentation

### (Optional): Suggest a solution

Make it possible to define extra environment files with the help of a .binder.yaml file

**Comment by consideRatio** [comment]
Your requirements.txt file can link to other requirements.txt files i think, right?

**Comment by biphasic** [comment]
that could be, but my main point is that the base requirements of the package are not always the same as the ones needed in a Binder env. In my case, the tutorial notebooks that I'd like users to be able to run require other large packages that I don't want to include in the root requirements.txt

**Comment by betatim** [comment]
You can create a `.binder/` directory in your repository and files in that will take precedent over the repo root. That lets you have different requirements for tutorial notebooks and such.

**Comment by biphasic** [comment]
this worked perfectly! As I didn't see any note about that in the docs, I added a line in a PR: https://github.com/binder-examples/requirements/pull/25
