### ISSUE TITLE
Link to donation page does not work as intended

### ISSUE THREAD

**Issue by schnaitter** [jupyterhub/mybinder.org-user-guide#289]
https://github.com/jupyterhub/mybinder.org-user-guide/blob/1036fa5f1b527426ed4a902abb7761c4149a9985/doc/about/support.md?plain=1#L11

The donation link on https://mybinder.readthedocs.io/en/latest/about/support.html or mybinder.org does not work. It redirects to https://www.bonterratech.com.

**Comment by rgaiacs** [comment]
In https://github.com/jupyterhub/team-compass/issues/742, a new URL was provided:

> They told me that they recommendation is to use the following Jupyter donate link for now:
> 
> https://numfocus.org/donate-to-jupyter
